import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Building,
  Building2,
  Cable,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Code2,
  Cog,
  Copy,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  FileSignature,
  Filter,
  Fingerprint,
  FlaskConical,
  FolderSearch,
  Gauge,
  HeartPulse,
  IdCard,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  ListChecks,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  MailWarning,
  Menu,
  PieChart,
  Play,
  PlugZap,
  Plus,
  RefreshCw,
  Repeat,
  Scale,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Terminal,
  User,
  UserCheck,
  UserCog,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  brain: Brain,
  building: Building,
  "building-2": Building2,
  cable: Cable,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "code-2": Code2,
  cog: Cog,
  copy: Copy,
  database: Database,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "file-signature": FileSignature,
  filter: Filter,
  fingerprint: Fingerprint,
  "flask-conical": FlaskConical,
  "folder-search": FolderSearch,
  gauge: Gauge,
  "heart-pulse": HeartPulse,
  "id-card": IdCard,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  landmark: Landmark,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  "log-out": LogOut,
  mail: Mail,
  "mail-warning": MailWarning,
  menu: Menu,
  "pie-chart": PieChart,
  play: Play,
  "plug-zap": PlugZap,
  plus: Plus,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  terminal: Terminal,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  users: Users,
  wallet: Wallet,
  x: X,
};

export interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 16, className, strokeWidth = 2 }: IconProps) {
  const Cmp = ICONS[name] ?? CircleAlert;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
